- name: Demo on Printing
  hosts: localhost
  tasks:
    - name: Print Hello World
      ansible.builtin.debug:
        msg: Hello World

- name: Demo on vars
  hosts: localhost
  vars:
    URL: example.com
  tasks:
    - name: Print a variable
      ansible.builtin.debug:
        msg: "{{ URL }}"
## Given the variable in double quotes, Good to give variable in double/single quotes, Because it will fail in some scenarios if quotes are not provided.
# In the key: value, if the value is just variable or if the values starts with variable then it will fail

- name: Demo on task level vars
  hosts: localhost
  vars:
    URL: play.example.com
  tasks:
    - name: Print task variable
      ansible.builtin.debug:
        msg: "{{ URL }}"
      vars:
        URL: task.example.com

    - name: Print play variable
      ansible.builtin.debug:
        msg: "{{ URL }}"

- name: Demo on roles variables
  hosts: localhost
  roles:
    - demo
